# -*- coding: utf-8 -*-
"""cartoonify image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sUzK8btBIpwYDL9JV3xxnZbwUH_LwTUx
"""

import cv2
import matplotlib.pyplot as plt

img = cv2.imread('/content/main-qimg-1479e808ebf7083e94195ee94a89c29b-lq.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

gsimg = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
rs2 = cv2.resize(gsimg, (960, 540))
plt.imshow(rs2, cmap='gray')

sgscl = cv2.medianBlur(gsimg, 5)
rs3 = cv2.resize(sgscl, (960, 540))
plt.imshow(rs3, cmap='gray')

ge = cv2.adaptiveThreshold(sgscl, 255, 
  cv2.ADAPTIVE_THRESH_MEAN_C, 
  cv2.THRESH_BINARY, 9, 9)

rs4 = cv2.resize(ge, (960, 540))
plt.imshow(rs4, cmap='gray')

cimg = cv2.bilateralFilter(img, 9, 300, 300)
rs5 = cv2.resize(cimg, (960, 540))
plt.imshow(rs5, cmap='gray')

ci = cv2.bitwise_and(cimg, cimg, mask=ge)

rs6 = cv2.resize(ci, (1500, 960))

plt.imshow(rs6, cmap='gray')
plt.savefig('output.png')

